services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users_db
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

  user-service:
    build: ./user-service
    depends_on:
      - postgres
      - rabbitmq
    env_file:
      - ./user-service/.env
    ports:
      - "3000:3000"

  notification-service:
    build: ./notification-service
    depends_on:
      - redis
      - rabbitmq
    env_file:
      - ./notification-service/.env
    command: sh -c "sleep 5 && node dist/main.js"